### PR TITLE
Added More Video tutorials Resources, DP, DSA

### PR DESCRIPTION
**Pull request by shuklaritvik06**

### CODE REVIEW

**Comment by includestdlibrary** [comment]
@MRslimcoder  please review this

**Review by MRslimcoder — APPROVED** [review]

**Comment by MRslimcoder** [comment]
@shuklaritvik06 LGTM

**Comment by MRslimcoder** [comment]
@shuklaritvik06  PR is merged.

**Comment by MRslimcoder** [comment]
@all-contributors add @shuklaritvik06 for content.

**Pull request merged**
