### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AvidCoder101**
#83

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
Looks more organised and better now @AvidCoder101

**Review by MRslimcoder — APPROVED** [review]
LGTM just move community section above extra,
extra section should be in bottom.

**Comment by AvidCoder101** [comment]
I have fixed that @MRslimcoder, thanks

**Review by MRslimcoder — APPROVED** [review]
LGTM

**Comment by MRslimcoder** [comment]
@AvidCoder101 @CodingSpecies Thank you so much.

**Pull request merged**
