### PR TITLE
Image Center

### PR DESCRIPTION
**Pull request by MRslimcoder**
@CodingSpecies & @AvidCoder101 please review.

### CODE REVIEW

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
@MRslimcoder I have checked what the README looks like with it, and it doesn't seem to be in the middle

**Comment by AvidCoder101** [comment]
Perhaps you could do:

``` html
<p align="center">
  <img>
</p>
```

**Comment by MRslimcoder** [comment]
> Perhaps you could do:
> 
> ```
> <p align="center">
>   
> </p>
> ```
> 
> This would work

Are you sure? can you please check my branch and see changes.

**Comment by MRslimcoder** [comment]
My branch: https://github.com/jobream/List-of-Learning-Resources/tree/MRslimcoder-patch-1

**Review by AvidCoder101 — APPROVED** [review]
@MRslimcoder, sorry, when I loaded the rich diff, it seemed like it was not in the middle. LGTM 👍🏻

**Comment by MRslimcoder** [comment]
Guy's adding more issues which I found in this project.

**Pull request merged**
