### PR TITLE
Addition of Competitive Programming Resources

### PR DESCRIPTION
**Pull request by Mannuel25**
I added some competitive programming resources

### CODE REVIEW

**Review by MRslimcoder — APPROVED** [review]
LGTM

**Comment by MRslimcoder** [comment]
@Mannuel25 squash commits into one and then push your single commit within branch.

**Comment by Mannuel25** [comment]
> @Mannuel25 squash commits into one and then push your single commit within branch.

Okay, I'd work on that. Thanks.

**Comment by MRslimcoder** [comment]
@Mannuel25 I squash commit's by myself, thank you for sending us Pr.

@all-contributors add @Mannuel25 for content.

**Comment by Mannuel25** [comment]
> @Mannuel25 I squash commit's by myself, thank you for sending us Pr.

Haha, it's the least I could do 🤗

**Comment by Mannuel25** [comment]
> @Mannuel25 I squash commit's by myself, thank you for sending us Pr.

Okayy, so in subsequent PRs I'd be making, I shouldn't bother about squashing commits right, it'd be taking care of?

**Pull request merged**
