### PR TITLE
moved the fork to the top

### PR DESCRIPTION
**Pull request by CodingSpecies**
#70

### CODE REVIEW

**Comment by MRslimcoder** [comment]
@CodingSpecies add fork description in all sections.

**Comment by CodingSpecies** [comment]
Done

**Review by MRslimcoder — APPROVED** [review]
LGTM

**Comment by MRslimcoder** [comment]
@CodingSpecies can you guide me how can I join "Zero To Mastery", "Make Contributors" and "CodingContributorsLair".

**Pull request merged**
