### PR TITLE
An idea to update the README.md

### PR DESCRIPTION
**Pull request by CodingSpecies**
To update and change the README.md, from the issue #56 , I made separate sections, and put the resources in tables. Please take a look and see if you approve.

### CODE REVIEW

**Comment by MRslimcoder** [comment]
@CodingSpecies Looks good @AvidCoder101 what you think about it?

**Comment by AvidCoder101** [comment]
LGTM, I like the way @CodingSpecies has organised it. Good job 🙂

**Comment by CodingSpecies** [comment]
I changed the icons, and changed the whole README.md to see how it would look.

**Comment by MRslimcoder** [comment]
@CodingSpecies Good Job, I need to review it and see impact of this and then merged this PR.

**Comment by MRslimcoder** [comment]
@CodingSpecies Good Job, Your PR is merged. I will share more issues on #56

**Comment by CodingSpecies** [comment]
Thank you @MRslimcoder , also, is it possible to be part of the organisation please?

**Comment by MRslimcoder** [comment]
> Thank you @MRslimcoder , also, is it possible to be part of the organisation please?

I will ask owner for that.

**Pull request merged**
