### PR TITLE
contribution on web development roadmap.

### PR DESCRIPTION
**Pull request by usama-nayab**
I contributed here by describing the roadmap of web development in 2022

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@usama-nayab Please remove the changes made in the .all-contributorsrc file, as we will do that ourselves after. Thank you

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@usama-nayab thanks for adding a new section!
However, the format needs altering.

- [ ] Please move the:
image
to the roadmap.md file.

- [ ] remove empty lines from 106 - 110 please.

## After that, I can merge this, and it will be good to go!
Thank you.

**Review by TheSlimCoder — CHANGES_REQUESTED** [review]
@usama-nayab please remove yourself from **.all-contributorsrc** and work on changes suggested by @CodingSpecies

**Comment by AvidCoder101** [comment]
@usama-nayab I am closing this PR due to inactivity. Please feel free to reopen it if you would like to make changes :)

**Pull request closed without merging**
