### PR TITLE
Update CompetitiveProgramming.md

### PR DESCRIPTION
**Pull request by JayantGoel001**

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@JayantGoel001 , the 6 links you have added is already in the README.md. It is in the preview of the competitive programming. 
image

**Comment by CodingSpecies** [comment]
Please may you remove the 6, and perhaps add a resource that is not in our lists already. Thank you.

**Comment by CodingSpecies** [comment]
I think it looks good now.

**Review by CodingSpecies — APPROVED** [review]
I think this can be merged.

**Comment by JayantGoel001** [comment]
> I think this can be merged.

Thanks👍

**Comment by CodingSpecies** [comment]
@all-contributors please add @JayantGoel001 for content

**Pull request merged**
