### PR TITLE
Added more resources

### PR DESCRIPTION
**Pull request by labheshwar**

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@labeshsharma please revert the changes from saying `here is a few from our huge range`, to back to `here is 5 from our huge range`. Thank you.

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
please remove empty line number 33 @labeshsharma . Thank you

**Comment by labheshwar** [comment]
> @labeshsharma please revert the changes from saying `here is a few from our huge range`, to back to `here is 5 from our huge range`. Thank you.

Done

**Review by CodingSpecies — APPROVED** [review]

**Comment by CodingSpecies** [comment]
@all-contributors please add @labheshwar for content

**Pull request merged**
